Load balancer

diff --git a/0x0F-load_balancer/1-install_load_balancer b/0x0F-load_balancer/1-install_load_balancer
--- a/0x0F-load_balancer/1-install_load_balancer
+++ b/0x0F-load_balancer/1-install_load_balancer
@@ -21,3 +21,10 @@ backend webservers
 " | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
 sudo systemctl enable haproxy
 sudo systemctl restart haproxy
+
+if ! systemctl is-active haproxy >/dev/null; then
+    echo "HAProxy failed to start"
+    exit 1
+
+fi
+exit 0
